---
- include_vars: "{{ nodesfile }}"

- name: Copy private key into place
  template: src=hadoop_rsa dest=/home/{{ hadoop_user }}/.ssh/hadoop_rsa owner={{ hadoop_user }} group={{ hadoop_group}} mode=0600

- name: Copy slaves into place
  template: src=slaves dest=/usr/local/hadoop/etc/hadoop/slaves owner={{ hadoop_user }} group={{ hadoop_group}}

- name: prepare known_hosts
  lineinfile: 
    dest=/home/{{ hadoop_user }}/.ssh/known_hosts
    create=yes
    state=present
    line="{{ lookup('pipe', 'ssh-keyscan -t rsa '+item.ip) }}"
    regexp="^{{ item.ip }}"
    owner={{ hadoop_user }}
    group={{ hadoop_group }}
  with_items: "{{ nodes }}"
  
- name: add 0.0.0.0 to known_hosts for secondary namenode
  lineinfile: 
    dest=/home/{{ hadoop_user }}/.ssh/known_hosts
    create=yes
    state=present
    line="{{ lookup('pipe', 'ssh-keyscan -t rsa 0.0.0.0') }}"
    regexp="^0.0.0.0"
    owner={{ hadoop_user }}
    group={{ hadoop_group }}
