---
- name: Copy private key into place
  template: src=hadoop_rsa dest=/home/{{ hadoop_user }}/.ssh/hadoop_rsa owner={{ hadoop_user }} group={{ hadoop_group}} mode=0600

- name: Copy slaves into place
  template: src=slaves dest=/usr/local/hadoop/etc/hadoop/slaves owner={{ hadoop_user }} group={{ hadoop_group}}

- name: ensure hostkeys is a known host
  lineinfile: 
    dest=/home/{{ ansible_user }}/.ssh/known_hosts
    create=yes
    state=present
    line="{{ lookup('pipe', 'ssh-keyscan -t rsa '+item.ip) }}"
    regexp="^{{ item.ip }}"
  with_items: "{{ nodes }}"